# NumPy Assignment

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

In [6]:
def my_vandermonde(x, N=None, increasing=True):
    """ The columns of the output matrix are powers of the input vector. 
    The order of the powers is determined by the increasing boolean argument."""
    
    _array = np.array(x)          # creates an array
    mylist = []                   # creates a list
    
    if N == None:                 # check for parameter N
        N = len(x)
    else:
        N = N
           
    for i in range(N):
        mylist.append(_array**i)   # list of array to different powers

    myMatrix = np.matrix(np.array(mylist))
    myMatrixT = myMatrix.T
        
    if increasing==False:            # decreasing order display
        myMatrixT=np.flip(myMatrixT, axis=1)   
   
    return myMatrixT

In [7]:
_vector = [1, 2, 3, 5]
print('original vector:', _vector)
my_vandermonde(_vector,increasing=False)

original vector: [1, 2, 3, 5]


matrix([[  1,   1,   1,   1],
        [  8,   4,   2,   1],
        [ 27,   9,   3,   1],
        [125,  25,   5,   1]], dtype=int32)

In [8]:
_vector = [1, 2, 3, 5]
print('original vector:', _vector)
my_vandermonde(_vector,3, increasing=False)

original vector: [1, 2, 3, 5]


matrix([[ 1,  1,  1],
        [ 4,  2,  1],
        [ 9,  3,  1],
        [25,  5,  1]], dtype=int32)

In [9]:
_vector = [1, 2, 3, 5]
print('original vector:', _vector)
my_vandermonde(_vector,increasing=True)

original vector: [1, 2, 3, 5]


matrix([[  1,   1,   1,   1],
        [  1,   2,   4,   8],
        [  1,   3,   9,  27],
        [  1,   5,  25, 125]], dtype=int32)

In [10]:
x = np.array([1, 2, 3, 5])
a = np.vander(x,increasing=True)
a


array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [11]:
x = np.array([1, 2, 3, 5])
a = np.vander(x,increasing=False)
a


array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [12]:
x = np.array([1, 2, 3, 5])
a = np.vander(x,3, increasing=False)
a


array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])